# Generated by Django 2.1.5 on 2019-01-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_upl',
            field=models.FileField(blank=True, upload_to='app/static/img/posts_img'),
        ),
    ]
