# Generated by Django 2.1.5 on 2019-01-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_posts_image_upl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image_upl',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
