# Generated by Django 2.1.5 on 2019-01-27 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190127_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.CharField(default=datetime.datetime(2019, 1, 27, 17, 15, 17, 531230), max_length=40),
        ),
    ]
